<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <template #start>
          <ion-buttons>
            <ion-menu-button></ion-menu-button>
          </ion-buttons>
        </template>
        <ion-title>Reports</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true" class="p-4">
      <div class="space-y-4">
        <!-- Generate Report Button -->
        <ion-card class="shadow-md">
          <ion-card-content class="pt-6">
            <ion-button expand="block" color="primary" @click="generateReport">
              <template #start><ion-icon :icon="documentOutline"></ion-icon></template>
              Generate New Report
            </ion-button>
          </ion-card-content>
        </ion-card>

        <!-- Loading State -->
        <div v-if="isLoading" class="space-y-4">
          <ion-skeleton-text animated></ion-skeleton-text>
          <ion-skeleton-text animated></ion-skeleton-text>
        </div>

        <!-- Reports List -->
        <div v-else class="space-y-3">
          <ion-card v-for="report in reports" :key="report.id" class="shadow-md">
            <ion-card-header>
              <ion-card-title class="flex items-center justify-between">
                <span>{{ report.title }}</span>
                <ion-badge color="primary">{{ report.type }}</ion-badge>
              </ion-card-title>
            </ion-card-header>
            <ion-card-content>
              <div class="space-y-2 text-sm">
                <div class="flex justify-between">
                  <span class="text-gray-600">Generated By:</span>
                  <span class="font-medium">{{ report.generatedBy }}</span>
                </div>
                <div class="flex justify-between">
                  <span class="text-gray-600">Date:</span>
                  <span class="font-medium">{{ report.generatedDate }}</span>
                </div>
              </div>
              <p class="text-sm text-gray-600 mt-3">{{ report.description }}</p>
              <div class="flex gap-2 mt-4">
                <ion-button size="small" expand="block">
                  <template #start><ion-icon :icon="eyeOutline"></ion-icon></template>
                  View
                </ion-button>
                <ion-button size="small" expand="block" fill="outline">
                  <template #start><ion-icon :icon="downloadOutline"></ion-icon></template>
                  Download
                </ion-button>
              </div>
            </ion-card-content>
          </ion-card>
        </div>

        <div v-if="!isLoading && reports.length === 0" class="text-center py-12">
          <ion-icon :icon="documentTextOutline" class="text-6xl text-gray-300 mb-4"></ion-icon>
          <p class="text-gray-600">No reports available</p>
        </div>

        <!-- Error State -->
        <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
          {{ error }}
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonButton,
  IonIcon,
  IonBadge,
  IonButtons,
  IonMenuButton,
  IonSkeletonText,
} from '@ionic/vue'
import {
  documentOutline,
  documentTextOutline,
  eyeOutline,
  downloadOutline,
} from 'ionicons/icons'
import { ref, onMounted } from 'vue'
import api from '@/lib/api'
import type { Report } from '@/lib'

const reports = ref<Report[]>([])
const isLoading = ref(false)
const error = ref('')

onMounted(() => {
  loadReports()
})

const loadReports = async () => {
  isLoading.value = true
  error.value = ''

  try {
    const response = await api.get('/reports')
    reports.value = response.data
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Failed to load reports'
    console.error('Reports error:', err)
  } finally {
    isLoading.value = false
  }
}

const generateReport = async () => {
  isLoading.value = true
  error.value = ''

  try {
    const response = await api.post('/reports/generate', {})
    reports.value = [response.data, ...reports.value]
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Failed to generate report'
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
.report-page {
  display: grid;
  gap: 1.5rem;
}
</style>
