import { test, expect } from '@playwright/test'
import fs from 'fs'
import path from 'path'

// This is a scaffolded smoke test — it expects environment variables for test
// accounts and will not create or delete users. Confirm test-account creation
// before enabling the full workflow assertions.

const accounts = {
  vpaa: process.env.E2E_VPAA_EMAIL,
  dean: process.env.E2E_DEAN_EMAIL,
  chair: process.env.E2E_CHAIR_EMAIL,
  faculty: process.env.E2E_FACULTY_EMAIL,
  area: process.env.E2E_AREA_EMAIL,
  qa: process.env.E2E_QA_EMAIL,
  admin: process.env.E2E_ADMIN_EMAIL,
}

// Support token-based login using the local .e2e-credentials.json generated by the seeder.
const CRED_FILE = process.env.E2E_CREDENTIALS_FILE || path.join('C:', 'capstone', 'backend', 'backend-app', '.e2e-credentials.json')
let E2E_CREDENTIALS: any[] | null = null
if (fs.existsSync(CRED_FILE)) {
  try {
    E2E_CREDENTIALS = JSON.parse(fs.readFileSync(CRED_FILE, 'utf8'))
  } catch (e) {
    E2E_CREDENTIALS = null
  }
}

const PASSWORD = process.env.E2E_TEST_PASSWORD || 'Password123!'

test.describe('ADAMS E2E smoke', () => {
  test('landing page and login flow for VPAA', async ({ page }) => {
    // If a credentials file with tokens exists, pre-seed localStorage to skip interactive login/2FA
    // Prefer explicit token env var if provided
    const vpaaToken = process.env.E2E_VPAA_TOKEN || (E2E_CREDENTIALS && E2E_CREDENTIALS.find((c) => c.role === 'vpaa')?.token)
    if (vpaaToken) {
      await page.addInitScript((token) => {
        window.localStorage.setItem('auth_token', token)
      }, vpaaToken)
    }

    await page.goto('/')
    await expect(page).toHaveTitle(/ADAMS|Accreditation/)

    // If token-based credentials are present, we've already set localStorage and should be on dashboard
    if (vpaaToken) {
      await expect(page.locator('h1')).toContainText(/VPAA|Dashboard|VPAA Dashboard/)
      const avatarCount = await page.locator('img[alt="Profile photo"], .vpaa-avatar, .app-header img').count()
      expect(avatarCount).toBeGreaterThan(0)
      return
    }

    // Open login and perform interactive login/2FA
    await page.goto('/login')
    await expect(page.locator('input#email')).toBeVisible()

    // If no VPAA account configured, skip assertions
    if (!accounts.vpaa) {
      test.skip()
      return
    }

    await page.fill('input#email', accounts.vpaa)
    await page.fill('input#password', PASSWORD)
    await page.click('button[type="submit"]')

    // Wait for 2FA input or immediate redirect
    const twoFa = page.locator('input[placeholder*="6-digit"], input[name="code"]')
    if (await twoFa.count()) {
      // Assume test harness sets a known code in env or uses test mode.
      const code = process.env.E2E_2FA_CODE || '123456'
      await twoFa.fill(code)
      await page.click('button[type="submit"]')
    }

    // Dashboard should appear
    await expect(page.locator('h1')).toContainText(/VPAA|Dashboard|VPAA Dashboard/)

    // Check profile presence
    await expect(page.locator('img[alt="Profile photo"], .vpaa-avatar, .app-header img')).toHaveCountGreaterThan(0)
  })
})
