<template>
  <ion-page>
    <ion-header :translucent="true">
      <ion-toolbar>
        <template #start>
          <ion-buttons>
            <ion-menu-button></ion-menu-button>
          </ion-buttons>
        </template>
<<<<<<< HEAD
        <ion-title>Reports</ion-title>
      </ion-toolbar>
    </ion-header>

    <ion-content :fullscreen="true" class="p-4">
      <div class="space-y-4">
        <!-- Generate Report Button -->
        <ion-card class="shadow-md">
          <ion-card-content class="pt-6">
            <ion-button expand="block" color="primary" @click="generateReport">
              <template #start><ion-icon :icon="documentOutline"></ion-icon></template>
              Generate New Report
            </ion-button>
          </ion-card-content>
        </ion-card>

        <!-- Loading State -->
        <div v-if="isLoading" class="space-y-4">
          <ion-skeleton-text animated></ion-skeleton-text>
          <ion-skeleton-text animated></ion-skeleton-text>
=======
        <p>Generate institutional compliance scorecards and area-by-area breakdowns.</p>
        <div class="card-action">
          <app-button variant="primary" block>
            Generate Report
          </app-button>
        </div>
      </app-card>

      <app-card variant="elevated" clickable>
        <template #header>
          <h3>Submission Trends</h3>
        </template>
        <p>Track submission rates and timeline adherence across the academic year.</p>
        <div class="card-action">
          <app-button variant="primary" block>
            View Trends
          </app-button>
        </div>
      </app-card>

      <app-card variant="elevated" clickable>
        <template #header>
          <h3>Area Performance</h3>
        </template>
        <p>Analyze performance metrics by accreditation area and program.</p>
        <div class="card-action">
          <app-button variant="primary" block>
            View Analysis
          </app-button>
>>>>>>> 3c4a98959b6b6532b97c22c03523a7964c38f154
        </div>

<<<<<<< HEAD
        <!-- Reports List -->
        <div v-else class="space-y-3">
          <ion-card v-for="report in reports" :key="report.id" class="shadow-md">
            <ion-card-header>
              <ion-card-title class="flex items-center justify-between">
                <span>{{ report.title }}</span>
                <ion-badge color="primary">{{ report.type }}</ion-badge>
              </ion-card-title>
            </ion-card-header>
            <ion-card-content>
              <div class="space-y-2 text-sm">
                <div class="flex justify-between">
                  <span class="text-gray-600">Generated By:</span>
                  <span class="font-medium">{{ report.generatedBy }}</span>
                </div>
                <div class="flex justify-between">
                  <span class="text-gray-600">Date:</span>
                  <span class="font-medium">{{ report.generatedDate }}</span>
                </div>
              </div>
              <p class="text-sm text-gray-600 mt-3">{{ report.description }}</p>
              <div class="flex gap-2 mt-4">
                <ion-button size="small" expand="block">
                  <template #start><ion-icon :icon="eyeOutline"></ion-icon></template>
                  View
                </ion-button>
                <ion-button size="small" expand="block" fill="outline">
                  <template #start><ion-icon :icon="downloadOutline"></ion-icon></template>
                  Download
                </ion-button>
              </div>
            </ion-card-content>
          </ion-card>
=======
      <app-card variant="elevated" clickable>
        <template #header>
          <h3>Export Data</h3>
        </template>
        <p>Export compliance data in PDF, Excel, or CSV formats for external review.</p>
        <div class="card-action">
          <app-button variant="primary" block>
            Export
          </app-button>
>>>>>>> 3c4a98959b6b6532b97c22c03523a7964c38f154
        </div>

        <div v-if="!isLoading && reports.length === 0" class="text-center py-12">
          <ion-icon :icon="documentTextOutline" class="text-6xl text-gray-300 mb-4"></ion-icon>
          <p class="text-gray-600">No reports available</p>
        </div>

        <!-- Error State -->
        <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
          {{ error }}
        </div>
      </div>
    </ion-content>
  </ion-page>
</template>

<script setup lang="ts">
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonCard,
  IonCardContent,
  IonCardHeader,
  IonCardTitle,
  IonButton,
  IonIcon,
  IonBadge,
  IonButtons,
  IonMenuButton,
  IonSkeletonText,
} from '@ionic/vue'
import {
  documentOutline,
  documentTextOutline,
  eyeOutline,
  downloadOutline,
} from 'ionicons/icons'
import { ref, onMounted } from 'vue'
import api from '@/services/api'
import type { Report } from '@/types'

const reports = ref<Report[]>([])
const isLoading = ref(false)
const error = ref('')

onMounted(() => {
  loadReports()
})

const loadReports = async () => {
  isLoading.value = true
  error.value = ''

  try {
    // Update with your actual reports endpoint
    const response = await api.get('/reports')
    reports.value = response.data
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Failed to load reports'
    console.error('Reports error:', err)
  } finally {
    isLoading.value = false
  }
}

const generateReport = async () => {
  isLoading.value = true
  error.value = ''

  try {
    // Update with your actual generate report endpoint
    const response = await api.post('/reports/generate', {})
    reports.value = [response.data, ...reports.value]
  } catch (err: any) {
    error.value = err.response?.data?.message || 'Failed to generate report'
  } finally {
    isLoading.value = false
  }
}
</script>

<style scoped>
<<<<<<< HEAD
=======
.page-container {
  display: grid;
  gap: var(--spacing-2xl);
}

.page-header {
  display: grid;
  gap: var(--spacing-md);
}

.page-header h1 {
  margin: 0;
  font-size: var(--text-3xl);
  font-weight: var(--font-weight-bold);
  color: var(--color-text);
}

.page-header p {
  margin: 0;
  color: var(--color-text-secondary);
}

.reports-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: var(--spacing-lg);
}

.card-action {
  margin-top: var(--spacing-lg);
}
>>>>>>> 3c4a98959b6b6532b97c22c03523a7964c38f154
</style>
